apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confserver-pv-claim
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
