apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sync-pv-claim2
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
