apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: curielogger
  ports:
    - name: service1
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: service2
      protocol: TCP
      port: 2112
      targetPort: 2112