apiVersion: v1
kind: Service
metadata:
  name: cp-service
spec:
  type: NodePort
  selector:
    app: cproxy
  ports: 
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30081
    - name: "https"
      port: 443
      targetPort: 443
      nodePort: 30444