apiVersion: apps/v1
kind: Deployment
metadata:
  name: curietasker
  labels:
    app: curietasker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctasker
  template:
    metadata:
      labels:
        app: ctasker
    spec:
      containers:
      - name: curietasker 
        image: curiefense/curietasker
     